BetaTesterSite/Controllers/PhaseCreationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Drive.v3;
using Google.Apis.Services;
using BetaTesterSite.Models;
using Microsoft.AspNetCore.Identity;

namespace BetaTesterSite.Controllers
{
    public class PhaseCreationController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly string parentFolder = "1ZmHTYNmAhknN9IiWczo2OpOX1oznxRgD";
        private readonly DAL.BetaTesterContext context;
        private readonly UserManager<DAL.Identity.User> userManager;

        public PhaseCreationController(DAL.BetaTesterContext context, IHostingEnvironment hostingEnvironment, UserManager<DAL.Identity.User> userManager)
        {
            _hostingEnvironment = hostingEnvironment;
            this.context = context;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.Run<IActionResult>(() => View());
        }

        public async Task<IActionResult> Create()
        {
            return await Task.Run<IActionResult>(() => View());
        }


        public async Task<IActionResult> Save([FromForm]string[] data, string name, string fileId)
        {
            if (name == null) return await Task.Run<IActionResult>(() => Json(false));


            var credentials = Autenticar();
            Google.Apis.Drive.v3.Data.File file;
            using (var service = OpenService(await credentials))
            {
                var memStream = new MemoryStream();
                var streamWriter = new StreamWriter(memStream);

                foreach (var item in data)
                    streamWriter.WriteLine(item);

                streamWriter.Flush();


                var fileMetadata = new Google.Apis.Drive.v3.Data.File() { Name = name };
                fileMetadata.Parents = new List<string>() { parentFolder };

                var request = service.Result.Files.Create(fileMetadata, new MemoryStream(memStream.ToArray()), "application/octet-stream");
                request.Fields = "id";
                request.Upload();
                file = request.ResponseBody;
            }

            var user = await userManager.GetUserAsync(User);
            var phase = new DAL.Phase
            {
                FileId = file.Id,
                UserId = user.Id,
                Name = name
            };

            this.context.Phase.Add(phase);

            if (!string.IsNullOrWhiteSpace(fileId))
            {
                using (var service = OpenService(await credentials))
                {
                    var request = service.Result.Files.Delete(fileId);
                    request.Execute();
                }

                var oldPhase = this.context.Phase.Single(x => x.FileId == fileId);
                this.context.Phase.Remove(oldPhase);
            }

            this.context.SaveChanges();

            return await Task.Run<IActionResult>(() => Json(true));
        }

        [HttpPost]
        public async Task<IActionResult> OpenArchive([FromForm]string id)
        {
            if (string.IsNullOrWhiteSpace(id)) return await Task.Run<IActionResult>(() => Json(false));

            try
            {
                List<List<string>> data = new List<List<string>>();
                var credentials = Autenticar();
                using (var service = OpenService(await credentials))
                {

                    var request = service.Result.Files.Get(id);
                    var stream = new System.IO.MemoryStream();
                    request.Download(stream);

                    stream.Seek(0, SeekOrigin.Begin);

                    using (StreamReader sr = new StreamReader(stream))
                    {
                        string s = "";
                        List<string> line;
                        while ((s = sr.ReadLine()) != null)
                        {
                            line = new List<string>();
                            var val = s.Split('_');
                            line.AddRange(val);
                            data.Add(line);
                        }
                    }
                }
                return await Task.Run<IActionResult>(() => Json(new { fileId = id, data = data }));
            }
            catch
            {
                return Json(false);
            }
        }

        [HttpPost]
        [ActionName("RemovePhase")]
        public async Task<IActionResult> RemovePhase(string id)
        {
            if (string.IsNullOrWhiteSpace(id)) return await Task.Run<IActionResult>(() => Json(false));

            var credentials = Autenticar();
            using (var service = OpenService(await credentials))
            {
                var request = service.Result.Files.Delete(id);
                request.Execute();
            }

            var phase = this.context.Phase.Single(x => x.FileId == id);
            this.context.Phase.Remove(phase);
            this.context.SaveChanges();

            return await Task.Run<IActionResult>(() => Json(true));
        }

        private static async Task<Google.Apis.Auth.OAuth2.UserCredential> Autenticar()
        {
            Google.Apis.Auth.OAuth2.UserCredential credentials;

            using (var stream = new System.IO.FileStream("client_id.json", System.IO.FileMode.Open, System.IO.FileAccess.Read))
            {
                var diretorioAtual = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
                var diretoriocredentials = System.IO.Path.Combine(diretorioAtual, "credential");

                credentials = Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.AuthorizeAsync(
                    Google.Apis.Auth.OAuth2.GoogleClientSecrets.Load(stream).Secrets,
                    new[] { Google.Apis.Drive.v3.DriveService.Scope.Drive },
                    "user",
                    System.Threading.CancellationToken.None,
                    new Google.Apis.Util.Store.FileDataStore(diretoriocredentials, true)).Result;
            }

            return await Task.Run<Google.Apis.Auth.OAuth2.UserCredential>(() => credentials);
        }

        private static async Task<Google.Apis.Drive.v3.DriveService> OpenService(Google.Apis.Auth.OAuth2.UserCredential credentials)
        {
            return await Task.Run<Google.Apis.Drive.v3.DriveService>(() => new Google.Apis.Drive.v3.DriveService(new Google.Apis.Services.BaseClientService.Initializer()
            {
                HttpClientInitializer = credentials
            }));
        }

        [HttpPost]
        [ActionName("ListIndexPhases")]
        public async Task<IActionResult> ListRecentPhases(int start)
        {
            var user = await userManager.GetUserAsync(User);
            var UserId = user.Id;

            var phases = (from y in this.context.PhasesIndexView
                     join upf in this.context.UserPhaseFav on new { y.PhaseId, UserId } equals new { upf.PhaseId, upf.UserId } into up
                     join pr in this.context.PhaseRate on new { y.PhaseId, UserId } equals new { pr.PhaseId, pr.UserId } into _pr
                     join u in this.context.User on y.UserId equals u.Id
                     from upf in up.DefaultIfEmpty()
                     from pr in _pr.DefaultIfEmpty()
                     orderby y.PhaseId descending
                     select new Models.PhasesIndexViewModel{
                         Completed = y.Completed,
                         UserId = y.UserId,
                         Dies = y.Dies,
                         FileId = y.FileId,
                         Name = y.Name,
                         PhaseId = y.PhaseId,
                         Played = y.Played,
                         Rating = y.Rating,
                         UserRate = pr != null? pr.Rate : 0,
                         Tested = y.Tested,
                         Fav = upf == null? false : true,
                         CreatorName = u.FirstName
                     }).Skip(start).Take(10);

            //var phases = this.context.PhasesIndexView.OrderByDescending(x => x.PhaseId).Take(10);

            return await Task.Run<IActionResult>(() => Json(new
            {
                recordsTotal = this.context.Phase.Count(),
                recordsFiltered = this.context.Phase.Count(),
                data = phases
            }));
        }

        [HttpPost]
        [ActionName("PhaseGraphData")]
        public async Task<IActionResult> PhaseGraphData(string fileId)
        {
            if (string.IsNullOrWhiteSpace(fileId)) return Json( new { Total = 0});

            var phase = this.context.Phase.Single(x => x.FileId == fileId);

            return await Task.Run<IActionResult>(() => Json(new { Total = phase.Played, Dies = phase.Dies, Completed = phase.Completed }));
        }
        

        [HttpPost]
        [ActionName("FavoritePhase")]
        public async Task<IActionResult> FavoritePhase(int? phaseId)
        {
            if (!phaseId.HasValue) return Forbid();

            var user = await userManager.GetUserAsync(User);
            
            if(this.context.UserPhaseFav.Any(x => x.PhaseId == phaseId && x.UserId == user.Id))
            {
                var userPhaseFav = this.context.UserPhaseFav.Single(x => x.PhaseId == phaseId && x.UserId == user.Id);
                this.context.UserPhaseFav.Remove(userPhaseFav);
            }
            else
            {
                this.context.UserPhaseFav.Add(new DAL.UserPhaseFav
                {
                    PhaseId = phaseId.Value,
                    UserId = user.Id
                });
            }
            this.context.SaveChanges();

BetaTesterSite/Views/PhaseCreation/Index.cshtml
@{
    ViewData["Title"] = "Fases";
}

<style type="text/css">
    .no-background {
        background-color: rgba(255,255,255, 0);
    }

    @@media screen and (min-width: 768px) {
        #RateModal:before {
            display: inline-block;
            vertical-align: middle;
            content: " ";
            height: 100%;
        }
    }

    #RateModal .modal-dialog {
        display: inline-block;
        text-align: center;
        vertical-align: middle;
    }
    .back {
        list-style-type: none;
        padding: 0;
        float: left;
    }

        .back li {
            width: 40px;
            height: 40px;
        }
        
        .back li img:not(.trapImg) {
            width: 40px;
            height: 40px;
            margin: -20px -13px;
        }

    .form-control {
        border-radius: 0;
    }

    .trapImg {
        position: absolute;
        height: 15px;
        width: 15px;
        margin: -7px -2px;
        background-color: rgba(255,255,255,.4);
        border-radius: 2px;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <div class="card bg-light">
            <div class="card-header">
                Fases Mais Recentes
            </div>
            <div class="card-body">
                <table id="phaseTable" class="datatable display table table-sm table-bordered table-striped" style="border-collapse: collapse !important; width: 100%">
                    <thead>
                        <tr>
                            <th style="width:45%;">Nome</th>
                            <th style="width:30%;">Criador</th>
                            <th style="width:15%;">Avaliação</th>
                            <th style="text-align:center; width:10%;">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var modelPhaseRate = 0;

    var phaseTable = $('#phaseTable').DataTable({
        proccessing: true,
        serverSide: true,
        searching: true,
        lengthChange: false,
        autoWidth: false,
        dom: 'tip',
        ajax: {
            url: '@Url.Action("ListIndexPhases", "PhaseCreation")',
            type: 'POST'
        },
        columns: [
            {
                data: 'Name',
                render: function (data, type, row) {
                    return "<a href='javascript:void(0)' onclick='OpenPhase(" + JSON.stringify(row) + ")' >" + row.name + "</a>";
                }
            }
            , {
                data: 'CreatorName',
                render: function (data, type, row) {
                    return row.creatorName;
                }
            }
            , {
                data: 'Rating',
                render: function (data, type, row) {
                    if (row.rating == 0) return '<div style="cursor: pointer;" onclick="Rate(' + row.phaseId + ', ' + row.userRate + ')"><i class="far fa-star"></i></div>';
                    var stars = '<div style="cursor: pointer;" onclick="Rate(' + row.phaseId + ', ' + row.userRate + ')">';
                    for (var i = 0; i < row.rating; i++)
                        stars += '<i class="fas fa-star" style="color:gold;"></i>&nbsp;';
                    return stars + '</div>';
                }
            }
            , {
                orderable: false,
                data: null,
                className: 'text-center',
                render: function (data, type, row) {
                    var icon = row.fav ? '<i class="fas fa-star"></i>' : '<i class="far fa-star"></i>';

                    return "<a href='javascript:void(0)' onclick='Fav(" + row.phaseId + ")'>" + icon + "</a>";
                }
            }
	    ]
    });

    function Fav(phaseId) {
        $.ajax({
            url: '@Url.Action("FavoritePhase", "PhaseCreation")',
            type: 'POST',
            datatype: 'JSON',
            data: { phaseId: phaseId },
            success: function (data) {
                if (data) {
                    $('#phaseTable').DataTable().ajax.reload();
                }
                else {
                    alert('Houve um erro ao favoritar.');
                }
            }
        });
    }
    function Rate(phaseId, _modelPhaseRate) {
        modelPhaseRate = _modelPhaseRate;

        $('.starRateDiv').find('svg').attr('data-prefix', 'far');
        $('.starRate').css('color', 'black');

        for (var i = 0; i < modelPhaseRate; i++) {
            $('#starRate-' + i).css('color', 'gold');
            $('#starRateDiv-' + i).find('svg').attr('data-prefix', 'fas');
        }

        $('#RateModal').modal('show');
        $('#RateModelPhaseId').val(phaseId);
    }
</script>


<div class="modal fade" id="RateModal" tabindex="-1" role="dialog" aria-hidden="true" style="text-align: center;">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content no-background" style=" border: 0">
            <div class="modal-body no-background">
                <input type="hidden" id="RateModelPhaseId" />
                <div class="row no-background">
                    <div class="col-md-12 text-center no-background" id="StarRateArea">
                        @for (int i = 0; i < 5; i++)
                        {
                            <div class="starRateDiv" style="display: inline-table; cursor:pointer;" id="starRateDiv-@(i)"><i class="far fa-star starRate" id="starRate-@(i)" style="font-size:2em;"></i></div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    window.setInterval(function () {
        $('.starRateDiv').mouseenter(function () {
            $('.starRateDiv').find('svg').attr('data-prefix', 'far');
            $('.starRate').css('color', 'black');

            var index = $(this).attr('id').split('-')[1];

            for (var i = 0; i <= index; i++) {
                $('#starRateDiv-' + i).find('svg').attr('data-prefix', 'fas');
                $('#starRate-' + i).css('color', 'gold');
            }
            $('.starRateDiv').unbind('mouseenter');

        });
    }, 100);

    $('#StarRateArea').on('mouseleave', function () {
        $('.starRateDiv').find('svg').attr('data-prefix', 'far');
        $('.starRate').css('color', 'black');

        for (var i = 0; i < modelPhaseRate; i++) {
            $('#starRateDiv-' + i).find('svg').attr('data-prefix', 'fas');
            $('#starRate-' + i).css('color', 'gold');
        }
    });

    $('.starRateDiv').click(function () {
        var index = $(this).attr('id').split('-')[1];
        modelPhaseRate = parseInt(index) + 1;
        $.ajax({
            url: '@Url.Action("SaveRate", "PhaseCreation")',
            type: 'POST',
            datatype: 'JSON',
            data: { phaseId: $('#RateModelPhaseId').val(), rate: modelPhaseRate },
            success: function (data) {
                if (data) {
                    $('#RateModal').modal('hide');
                    $('#phaseTable').DataTable().ajax.reload();
                }
                else {
                    alert('Houve um erro ao avaliar.');
                }
            }
        });
    });
</script>

<div class="modal fade bd-example-modal-lg" id="PhaseModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div style="user-select:none; width: 100%; height: 440px; position: relative; margin-bottom: 1em; overflow-x: auto; overflow-y: hidden; margin-top:1em;" unselectable="on" onselectstart="return false;" onmousedown="return false;">
                <div class="form-group listGroup" id="backListGroup">
                </div>
            </div>
            <div>
                <div id="graph" style="margin: 0 auto; height: 180px; line-height: 180px; text-align: center;"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    
    function OpenPhase(data) {
        $.ajax({
            url: '@Url.Action("OpenArchive", "PhaseCreation")',
            type: 'POST',
            data: { id: data.fileId },
            traditional: true,
            dataType: 'json',
			success: function (data) {
				if (data == false) {
                    alert('Erro ao carregar fase, recarregue a pagina e tente novamente.');
				}
				else {
                    LoadArchive(data.data);
				}
			}
        });

        if (data.played == 0) {
            $('#graph').html('<i>Não foi jogada ainda.</i>');
            return false;
        }

        var _data = [{ name: 'Mortes', y: data.dies, color: 'red' }
            , {
                name: 'Concluídas', y: data.completed, color: 'green'
            }];

        if (data.dies + data.completed < data.played) {
            _data.push({ name: 'Não Concluídas', y: (data.played - (data.dies + data.completed)), color: 'lightgrey' });

        }

        console.log(_data);
        Highcharts.chart('graph', {

            chart: {
                type: 'pie'
            },

            title: {
                text: null
            },

            credits: {
                enabled: false
            },

            exporting: {
                enabled: false
            },

            yAxis: {
                min: 0,
                max: data.played,
                lineWidth: 0,
                tickPositions: []
            },

            legend: {
                layout: 'vertical',
                align: 'bottom',
                verticalAlign: 'middle',
                itemMarginTop: 10,
                itemMarginBottom: 10
            },

            plotOptions: {
                pie: {
                    shadow: false,
                    center: ['50%', '50%'],
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },

            series: [
                {
                    name: 'Vezes',
                    size: '100%',
                    innerSize: '60%',
                    data: _data
                }]
        });
    }


    function LoadArchive(data) {
        $('.listGroup').empty();
        var uls = [];
        $.each(data, function (i, e) {
            var ul = $('<ul>', { id: 'back-' + (i + 1), class: 'back' });
            $.each(e, function (_i, _e) {
                var data = JSON.parse(_e);
                var _data = data.Block;
                var prevData = 0;
                var trap = data.Trap;

                if (_i != 0) {
                    prevData = JSON.parse(e[_i - 1]).Block;
                }
                var icon = GetIcon(_data);
                var iconTrap = '';

                if (trap != null) {
                    iconTrap = GetIcon(trap, 'trapImg', (_data == 0 ? 'margin: -7px 7px;' : ''));
                }

                if (_i != 0 && (prevData != 0 && prevData != 2) && _data == 1) {
                    icon = '<img src="/images/ground_tile2.png" />';
                }

                ul.append('<li class="form-control" id="backItem' + (i + 1) + '-' + _i + '"  data-value="' + _data + '" data-trap="' + trap + '" data-hFlipTrap="' + data.hFlipTrap + '" data-vFlipTrap="' + data.vFlipTrap + '">' + icon + iconTrap + '</li>');

            });
            uls.push(ul);
            ul = null;
        });
        $('#backListGroup').append(uls);
         

        $("#slider").slider('value', data.length);
        var totalWidth = data.length * 40;
        $('.listGroup').width(totalWidth);
        $('#PhaseModal').modal('show');
    }
      
    function GetIcon(id, _class) {
        var img = '<img ';
        if (_class != null) img += 'class="' + _class + '" ';

        switch (id) {
            case 1:
                return img + 'src="/images/ground_tile1.png" />';
            case 2:
                return img + 'src="/images/Personagem.png" />';
            case 3:
                return img + 'src="/images/ground-ramp-right_tile1.png" />';
            case 4:
                return img + 'src="/images/ground-ramp-left_tile1.png" />';
            case 5:
                return img + 'src="/images/flag.png" />';
            case 6:
                return img + 'src="/images/Serra.png" />';
            case 7:
                return img + 'src="/images/totem.png" />';
            default:
                return '&nbsp;';
        }
    }
</script>