BetaTesterSite/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BetaTesterSite.Models
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

BetaTesterSite/Models/Shared/DataTablesAjaxPostModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BetaTesterSite.Models.Shared
{
    public class DataTablesAjaxPostModel
    {
        public int draw { get; set; }
        public int? start { get; set; }
        public int? length { get; set; }
        public Search search { get; set; }

        public DataTablesAjaxPostModel()
        {
            this.search = new Search();
        }
    }
    
    public class Search
    {
        public string value { get; set; }
        public string regex { get; set; }
    }
}

BetaTesterSite/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BetaTesterSite.Controllers
{
    public class HistoryController : Controller
    {
        public IActionResult Index(int? typeId)
        {
            return View(typeId);
        }
    }
}

BetaTesterSite/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BetaTesterSite.DAL;

namespace ACATWeb.Controllers
{
    //[Authorize]
    [Authorize("SystemVariablesManager")]
    public class PermissionsController : Controller
    {
        private readonly BetaTesterSite.DAL.BetaTesterContext context;

        public PermissionsController(BetaTesterSite.DAL.BetaTesterContext context)
        {
            this.context = context;
        }

        //[Authorize("SystemVariablesManager")]
        public IActionResult Index()
        {
            ViewData["Policies"] = context.Policy.ToList();
            ViewData["PolicyRoles"] = context.PolicyRole.ToList();
            ViewData["Roles"] = context.Role.ToList();
            return View();
        }

        [HttpPost]
        //[Authorize("SystemVariablesManager")]
        public IActionResult Manage(int[] adminPolicyId, int[] guestPolicyId)
        {
            var roles = context.Role.ToList();

            var adminRoleId = roles.Single(x => x.NormalizedName == "ADMINISTRATOR").Id;
            var gustRoleId = roles.Single(x => x.NormalizedName == "GUEST").Id;

            ClearPolicyRoles();

            foreach (var policyId in adminPolicyId)
                context.PolicyRole.Add(new PolicyRole { PolicyId = policyId, RoleId = adminRoleId });

            foreach (var policyId in guestPolicyId)
                context.PolicyRole.Add(new PolicyRole { PolicyId = policyId, RoleId = gustRoleId });
            this.context.SaveChanges();

            return Json(true);
        }

        public void ClearPolicyRoles()
        {
            var policyRoles = context.PolicyRole.ToArray();
            for (int i = 0; i < policyRoles.Length; i++)
            {
                context.PolicyRole.Remove(policyRoles[i]);
            }
            this.context.SaveChanges();
        }

    }
}

BetaTesterSite/Controllers/PersonagensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BetaTesterSite.Controllers
{
    public class PersonagensController : Controller
    {
        public IActionResult Index(int? typeId)
        {
            return View(typeId);
        }
    }
}

BetaTesterSite/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BetaTesterSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BetaTesterSite.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<DAL.Identity.User> _signInManager;
        private readonly UserManager<DAL.Identity.User> userManager;
        private readonly DAL.BetaTesterContext context;

        public UserController(DAL.BetaTesterContext context, UserManager<DAL.Identity.User> userManager, SignInManager<DAL.Identity.User> signInManager)
        {
            this.userManager = userManager;
            this.context = context;
            this._signInManager = signInManager;
        }
        [Authorize(Policy = "UserManager")]
        public IActionResult Index()
        {
            return View();
        }


        [Authorize(Policy = "UserManager")]
        public IActionResult Manage(int? id)
        {
            var user = new Models.UserViewModel();
            ViewData["Roles"] = context.Role.ToList();
            if (id.HasValue)
                user = GetUserViewModels(context.User.SingleOrDefault(x => x.Id == id));
            return View(user);
        }

        [HttpPost]
        [ActionName("Manage")]
        [AllowAnonymous]
        public async Task<IActionResult> _Manage(UserViewModel model)
        {
            int userId;
            if (model.UserId.HasValue)
            {
                Update(model);
                userId = model.UserId.Value;
            }
            else
                userId = Create(model);

            if (userId != 0)
            {
                ClearUserRoles(userId);
                AddUserToRole(userId, (string.IsNullOrWhiteSpace(model.Role) ? "Administrator" : model.Role));
            }

            return await Task.Run<IActionResult>(() => Json(userId));
        }

        [AllowAnonymous]
        public int Create(UserViewModel model)
        {
            var id = _Create(model).Result;
            if (id != 0)
                AddUserToRole(id, "Administrator");

            return id;
        }

        [AllowAnonymous]
        public async Task<int> _Create(UserViewModel model)
        {
            var user = new DAL.Identity.User()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                UserName = model.Email,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                IsActive = model.IsActive,
                Password = model.Password
            };

            var identityResult = await this.userManager.CreateAsync(user, model.Password);
            if (identityResult.Succeeded)
                return user.Id;
            else
                return 0;
            //throw new Exception(string.Join(';', identityResult.Errors.Select(x => x.Code)));
        }

        [HttpPost]
        [ActionName("List")]
        public IActionResult _List(Models.Shared.DataTablesAjaxPostModel filter)
        {
            IQueryable<DAL.Identity.User> d;
            IEnumerable<Models.UserViewModel> _d;
            if (string.IsNullOrWhiteSpace(filter.search.value))
            {
                d = (from y in context.User where y.IsDeleted == false select y);
                _d = GetUserViewModels(d).Skip(filter.start ?? 0).Take(10);
            }
            else
            {
                d = (from y in context.User
                     where y.IsDeleted == false
                     where y.Email.ToUpper().Contains(filter.search.value.ToUpper()) || y.FirstName.ToUpper().Contains(filter.search.value.ToUpper())
                     select y);
                _d = GetUserViewModels(d).Skip(filter.start ?? 0).Take(10);
            }
            return Json(new
            {
                recordsTotal = d.Count(),
                recordsFiltered = d.Count(),
                data = _d
            });
        }

        [Authorize(Policy = "UserManager")]
        List<UserViewModel> GetUserViewModels(IQueryable<DAL.Identity.User> data)
        {
            return (from y in data
                    join ur in context.AspNetUserRoles on y.Id equals ur.UserId
                    join ro in context.Role on ur.RoleId equals ro.Id
                    select new BetaTesterSite.Models.UserViewModel()
                    {
                        UserId = y.Id,
                        FirstName = y.FirstName,
                        LastName = y.LastName,
                        Email = y.Email,
                        PhoneNumber = y.PhoneNumber,
                        IsActive = y.IsActive,
                        Role = ro.Description
                    }).ToList();
        }

        [Authorize(Policy = "UserManager")]
        UserViewModel GetUserViewModels(DAL.Identity.User data)
        {
            return new BetaTesterSite.Models.UserViewModel()
            {
                UserId = data.Id,
                FirstName = data.FirstName,
                LastName = data.LastName,
                Email = data.Email,
                PhoneNumber = data.PhoneNumber,
                IsActive = data.IsActive,
                Role = GetRoleByUserId(data.Id)
            };
        }

        [HttpPost]
        [ActionName("RemoveUser")]
        public async Task<IActionResult> RemoveUser(int id)
        {
            if (!context.User.Any(x => x.Id == id)) return Json(false);

            var user = context.User.Single(x => x.Id == id);
            user.IsDeleted = true;

            context.User.Update(user);
            context.SaveChanges();

            return await Task.Run<IActionResult>(() => Json(true));
        }

        [Authorize(Policy = "UserManager")]
        public void Update(UserViewModel model)
        {
            var user = context.User.Single(x => x.Id == model.UserId);

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.PhoneNumber = model.PhoneNumber;
            user.Password = model.Password;
            user.Email = model.Email;
            user.UserName = model.Email;
            user.IsActive = model.IsActive;
            if (!string.IsNullOrWhiteSpace(model.Password))
                user.PasswordHash = this.userManager.PasswordHasher.HashPassword(user, model.Password);

            this.userManager.UpdateAsync(user);

            this.context.User.Update(user);
            this.context.SaveChanges();
        }


        [Authorize(Policy = "UserManager")]
        public void ClearUserRoles(int userId)
        {
            var userRoles = this.context.AspNetUserRoles.Where(x => x.UserId.Equals(userId)).ToArray();
            for (int i = userRoles.Length - 1; i == 0; i--)
            {
                this.context.AspNetUserRoles.Remove(userRoles[i]);
            }
            this.context.SaveChanges();
        }

        [AllowAnonymous]
        public void AddUserToRole(int userId, string role)
        {
            var r = this.context.Role.Single(x => x.NormalizedName.Equals(role.ToUpper()));
            var anur = new DAL.Identity.AspNetUserRoles()
            {
                RoleId = r.Id,
                UserId = userId
            };

            this.context.Add(anur);
            this.context.SaveChanges();
        }

        [Authorize(Policy = "UserManager")]
        public string GetRoleByUserId(int id)
        {
            var r = (from y in context.User
                     join ur in context.AspNetUserRoles on y.Id equals ur.UserId
                     join ro in context.Role on ur.RoleId equals ro.Id
                     where y.Id == id
                     select ro.Description);

            return r.Count() > 0 ? r.First() : null;
            //return  r.Count() > 0 ? r.First() : null;
        }
    }
}

BetaTesterSite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Authorization

@inject BetaTesterSite.DAL.BetaTesterContext context
@inject SignInManager<BetaTesterSite.DAL.Identity.User> SignInManager
@inject UserManager<BetaTesterSite.DAL.Identity.User> UserManager
@inject IAuthorizationService AuthorizationService

@{
    var user = await UserManager.GetUserAsync(User);
}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/gif" href="~/images/logo.gif" />

    <link href="~/lib/jquery-ui/1.12.1/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-ui/1.12.1/jquery-ui.structure.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-ui/1.12.1/jquery-ui.theme.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" type="text/css" href="~/lib/datatables/jquery.dataTables.css" />*@

    <script src="~/lib/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/lib/popper.js/popper.js"></script>
    <script src="~/lib/fontawesome-free/5.1.0/web/js/all.js"></script>
    <script src="~/lib/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    @*<script type="text/javascript" src="~/lib/datatables/jquery.dataTables.js"></script>
        <script type="text/javascript" src="~/lib/datatables-responsive/dataTables.responsive.js"></script>*@


    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" />
    @*<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.2.4/css/select.bootstrap4.min.css" />*@

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.2.4/js/dataTables.select.min.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>

    <script type="text/javascript">
        $.extend(true, $.fn.dataTable.defaults, {
            "iDisplayLength": 10,
            'language': {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "_MENU_ resultados por página",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar",
                "oPaginate": {
                    "sNext": "Próximo",
                    "sPrevious": "Anterior",
                    "sFirst": "Primeiro",
                    "sLast": "Último"
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            }
        });
    </script>

    <script src="@Url.Content("~/js/site.js")"></script>
    <style>
        body {
            font-family: 'Raleway', sans-serif;
        }

        .shadow {
            box-shadow: 0.3rem 0.3rem .1rem rgba(0,0,0,.15) !important;
        }

        .tab-content {
            background: #E8E8E8;
        }

        .nav.nav-tabs a {
            color: black;
            background: #C4C4C4;
        }

            .nav.nav-tabs a.active {
                background: #E8E8E8;
                border: 0;
            }

        body {
            background: #fafafa;
        }

        .btn-info {
            background: #006053;
            border-color: #006053;
        }

        .btn-success {
            background: #006053;
            border-color: #006053;
        }

            .btn-success:hover {
                background: #00202f;
                border-color: #00202f;
            }

            .btn-success:active {
                background: #00202f !important;
                border-color: #00202f !important;
            }

        .odd {
            background: #e8e8e8;
        }

        .even {
            background: #fafafa;
        }
    </style>

</head>
<body>
    <img src="~/images/beta_test_water.png" style="width:100%; height: 82%; opacity: .5; position: fixed;" />
    <div id="loading" style="display: none;">
        <div style="position: fixed; top: 0; left: 0; height: 100%; width: 100%; background-color: rgba(0, 0, 0, 0.4); z-index: 10000;">
        </div>
        <div style="position: fixed; top: 50%; left: 50%; height: 200px; margin-top: -100px; width: 400px; margin-left: -200px; color: white; z-index: 10001; text-align: center;">
            <img src="~/images/logo.gif" style="width:100px; height:50px;" />
            <p class="hidden-sm" style="font-size: 24px;">Carregando...</p>
        </div>
    </div>
    <script type="text/javascript">
        var ajaxLoadTimeout;
        $(document).ajaxStart(function () {
            ajaxLoadTimeout = setTimeout(function () { $('#loading').show(); }, 500);
        });
        $(document).ajaxStop(function () {
            clearTimeout(ajaxLoadTimeout);
            $('#loading').hide();
        });
    </script>
    <nav class="navbar navbar-light bg-light navbar-expand-lg fixed-top" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="~/images/beta test_logo.png" width="80" height="50" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">História</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="@Url.Action("Index","History")?typeId=1">Beta Tester</a>
                            <a class="dropdown-item" href="@Url.Action("Index","History")?typeId=2">Jimmy in the Hell</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Personagens</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="@Url.Action("Index","Personagens")?typeId=1">Beta Tester</a>
                            <a class="dropdown-item" href="@Url.Action("Index","Personagens")?typeId=2">Jimmy in the Hell</a>
                        </div>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Criação de Fases</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                <a class="dropdown-item" href="@Url.Action("Index", "PhaseCreation")"><i class="fas fa-list-ul"></i>&nbsp;Fases</a>
                                <a class="dropdown-item" href="@Url.Action("Create", "PhaseCreation")"><i class="fas fa-th"></i>&nbsp;Criar de Fase</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0)" onclick="OpenModal()">Criação de Fase</a>
                            <script type="text/javascript">
                                function OpenModal() { $('#LoginModal').modal('show'); }
                            </script>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        if ((await AuthorizationService.AuthorizeAsync(User, "SystemVariablesManager")).Succeeded || (await AuthorizationService.AuthorizeAsync(User, "UserManager")).Succeeded)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cogs"></i>&nbsp;Ferramentas</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                    <a class="dropdown-item" href="@Url.Action("Index", "User")"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;Usuários</a>
                                    <a class="dropdown-item" href="@Url.Action("Index", "Permissions")"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;Permissões</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i>&nbsp;Olá, <b>@user.FirstName @user.LastName</b>!</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="@Url.Action("Info", "Account")">
                                    <i class="fa fa-user" aria-hidden="true"></i>&nbsp;Meu Perfil&nbsp;<small>
                                    </small>
                                </a>
                                <a class="dropdown-item" href="@Url.Action("LogOut", "Account")"><i class="fa fa-sign-out-alt" aria-hidden="true"></i>&nbsp;Sair</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0)" data-toggle="modal" data-target="#LoginModal" id="LoginOpenbutton">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" style="margin-top: 6em;">
        @RenderBody()

        @if (!User.Identity.IsAuthenticated)
        {
            Html.RenderPartial("~/Views/Shared/_Login.cshtml");
        }
    </div>

    @RenderSection("scripts", required: false)
    <div style="margin-top:3em;"></div>
    <div style="position: fixed; color: rgb(255, 211, 0); width: 100%; height: 24px; bottom: 0; left: 0; background-color: rgb(76, 78, 64); text-align: center; box-shadow: 0 -4px 8px 0 rgba(0, 0, 0, 0.2), 0 -6px 20px 0 rgba(0, 0, 0, 0.19); z-index: 1000; font-size: 0.8em; line-height: 24px;">
        Beta Tester :: 1.0 - Desenvolvido por <a href="javascript:void(0)" style="color: rgb(255, 211, 0)">Upside Down</a>.
    </div>
</body>
</html>